### ISSUE TITLE
Recursive options definitions causes problems with `typename`

### ISSUE THREAD

**Issue by csilvers** [Khan/genqlient#131]
As I understand it, if you have an option like `@genqlient(typename: "Foo")`, it applies not only to the field in question, but all child fields below it.  This causes problems.  In this case, change `generate/testdata/queries/TypeNames.graphql` to read like so:
```
# @genqlient(typename: "Resp")
query TypeNames {
  # @genqlient(typename: "User")
  user { id authMethods { provider email } }
  # @genqlient(typename: "Item")
  randomItem { id name } 
  # (ok to reuse the name as long as they match)
  # @genqlient(typename: "User")
  users { id authMethods { provider email } }
}
```
`make check` now fails with this error:
```
        generate_test.go:104: testdata/queries/schema.graphql:135: conflicting definition for User; this can indicate either a genqlient internal error, a conflict between user-specified type-names, or some very tricksy GraphQL field/type names: expected GraphQL type AuthMethod, got User
```

Looking in the debugger, it's failing on `if typ.GraphQLTypeName() != graphQLName {`: `graphQLName` is `User`, but `typ.GraphQLTypeName()` is `AuthMethod`.

**Comment by csilvers** [comment]
This also seems like it's a problem for `pointer: true`, though it's not a fatal one in that case.  If you change the query to be:
```
# @genqlient(typename: "Resp")
query TypeNames {
  # @genqlient(typename: "User", pointer: true)
  user { id name }
  # @genqlient(typename: "Item")
  randomItem { id name }
  # (ok to reuse the name as long as they match)
  # @genqlient(typename: "User", pointer: true)
  users { id name }
}
```
then the generated code includes code like:
```
                 +func (v *User) GetName() *string { return v.Name }
```

One could argue that's intentional -- though to me it's suprising -- and you can always turn it off with something like:
```
  # @genqlient(typename: "User", pointer: true)
  users { 
      # @genqlient(pointer: false)
      id 
      # @genqlient(pointer: false)
      name
   }
```

So I'm not filing this as a separate, related bug, though it's possible it is one.

**Comment by csilvers** [comment]
Ah, I think I was fooled by the fact the examples have a bunch of fields on one line.  When I change the query to:
```
# @genqlient(typename: "Resp")
query TypeNames {
  # @genqlient(typename: "User")
  user {
    id
    authMethods { provider email }
  }
  # @genqlient(typename: "Item")
  randomItem { id name }
  # (ok to reuse the name as long as they match)
  # @genqlient(typename: "User", pointer: true)
  users {
    id
    authMethods { provider email }
  }
}
```
everything is fine.

**Comment by dnerdy** [comment]
@csilvers did you eventually find the documentation describing this behavior? This behavior is called out [here](https://github.com/Khan/genqlient/blob/main/docs/genqlient_directive.graphql#L11-L13) and [here](https://github.com/Khan/genqlient/blob/main/docs/genqlient_directive.graphql#L41-L45).

**Comment by csilvers** [comment]
Yeah, I did find the docs!

**Comment by benjaminjkraft** [comment]
Yeah, this is perhaps a useful feature or perhaps a misfeature, but it's semi-intended!
