### ISSUE TITLE
Multiple `typename`s interacts badly with other options

### ISSUE THREAD

**Issue by csilvers** [Khan/genqlient#132]
I think it's known that combining options can cause issues.  Here's one: change generate/testdata/queries/TypeNames.graphql to:
```
# @genqlient(typename: "Resp")
query TypeNames {
  # @genqlient(typename: "User")
  user {
      # @genqlient(pointer: true)
      id
      name
  }
  # @genqlient(typename: "Item")
  randomItem { id name }
  # (ok to reuse the name as long as they match)
  # @genqlient(typename: "User")
  users {
      id
      # @genqlient(pointer: true)
      name
  }
}
```
genqlient considers that the two definitions of `User` match, even though they have conflicting pointer semantics.  One of them wins arbitrarily (seemingly the first one).

**Comment by csilvers** [comment]
This is probably another instance of #123 .

**Comment by benjaminjkraft** [comment]
Yep this is another case of #123!  The proposed fix would apply equally to both, so I'll call this a dupe and add a note about `typename` there.
