### ISSUE TITLE
Error when parsing config: cannot unmarshal !!seq into string

### ISSUE THREAD

**Issue by ivanvanderbyl** [Khan/genqlient#150]
**Describe the bug**

When providing a list of file paths for schema config, returns the error `cannot unmarshal !!seq into string`

**To Reproduce**

Run generate using the following `genqlient.yaml`:

```yaml
schema:
  - ./graph/file.gql

```

**Expected behavior**

It should parse the list of files

**genqlient version**

- `v0.3.0`

**Comment by benjaminjkraft** [comment]
Thanks for the report!  In v0.3.0, the syntax is `schema: ./graph/file.gql`; the list syntax is added on `main` but not yet in a release.
