### ISSUE TITLE
Hope to expose the type of fragment

### ISSUE THREAD

**Issue by Dreamacro** [Khan/genqlient#158]
**Is your feature request related to a problem? Please describe.**

When I'm using https://github.com/Yamashou/gqlgenc, when `.graphql` contains a fragment, go structure is exposed during generation. But it can't customize `client`. I tried changing the generator to this library but couldn't find a way to expose the fragment type.

**Describe the solution you'd like**

Let the fragment export by default, or set it via the configuration.

**Comment by benjaminjkraft** [comment]
Thanks for your question!  There's a bit more documentation about how genqlient handles fragments in the [FAQ](https://github.com/Khan/genqlient/blob/main/docs/FAQ.md#-shared-types-between-different-parts-of-the-query).  If that doesn't help answer your question, could you give more details about what you're trying to do?  For example an example query and a snippet of the code you want to write but can't would be very helpful to understand what you're getting at.

**Comment by Dreamacro** [comment]
@benjaminjkraft I'm sorry for my mistake. When the fragment starts with an uppercase letter it would export by default.

Thanks for your great work. 👍
