### ISSUE TITLE
Cannot use use_struct_references field in genqlient.yaml

### ISSUE THREAD

**Issue by AlexandrosMelissas** [Khan/genqlient#159]
**Describe the bug**
Cannot use use_struct_references field in genqlient.yaml. Error : "field use_struct_references not found in type generate.Config"

**To Reproduce**
use_struct_references: true in genqlient.yaml. It happens in generation time.

**Expected behavior**
I expect the code generation to happen successfully

**genqlient version**
I've tried both 0.2.0 and 0.3.0

**Comment by benjaminjkraft** [comment]
Thanks for the report! This feature isn't in a release yet, so if you want to install it you can use the latest main branch, e.g. `go run github.com/Khan/genqlient@main`.
