### ISSUE TITLE
directive to apply omitempty on nested fields

### ISSUE THREAD

**Issue by suhabe** [Khan/genqlient#165]
I'm getting this error when using the @genqlient directive on the following mutation and schema:

Error: 
`client.graphql:339: for is only applicable to operations and arguments`

Mutation:
```
# @genqlient(for: "AddAuthorInput.name", omitempty: true)
mutation AddAuthorWithPost($author: AddAuthorInput!) {
    addAuthor(input: [$author]) {
        author {
            id
        }
    }
}
```

Schema:
```
input AddAuthorInput {
	name: String
	posts: [PostRef!]
}

input PostRef {
	postID: ID
	postUuid: String
	title: String
	subPosts: [PostRef!]
}
```

Is the directive above written the correct way? I tried following the explanation at: https://github.com/Khan/genqlient/blob/main/docs/FAQ.md#-nullable-fields

Also, is possible to add a directive on a nested subfield? So for example, something like:
`# @genqlient(for: "AddAuthorInput.posts.title", omitempty: true)`

Is it possible to add a directive on a field of struct type that's nested in the top level type? So for example, something like:
`# @genqlient(for: "PostRef.title", omitempty: true)`

**Comment by suhabe** [comment]
Also, when the directive is applied to the entire query, I get this error:
`client.graphql:339: omitempty may only be used on optional arguments`

```
# @genqlient(omitempty: true)
mutation AddAuthorWithPost($author: AddAuthorInput!) {
    addAuthor(input: [$author]) {
        author {
            id
        }
    }
}
```

I was expecting the directive to apply omitempty everywhere in the query, including deeply nested fields of the input variable, regardless of whether they are optional or not. Or even better, to automatically figure out when to apply the omitempty to every argument or deeply nested field, depending on whether they are optional or not.

**Comment by suhabe** [comment]
By the way, this functionality is important when using Dgraph for the use case described here: https://discuss.dgraph.io/t/best-way-to-avoid-duplicate-xid-found/10369

Dgraph expects a block of a mutation's input to include only the XID field and have no other fields set in order for the block to be used as a reference to another block.

**Comment by suhabe** [comment]
After investigating further, I found that the best way to use genqlient with Dgraph is to have `omitempty` on every generated field and always make the field type a pointer (e.g. *int instead of int). The reason is that Dgraph relies on distinguishing between a zero value and no value.

Is there a global configuration option to enable these two changes to the generated code?

**Comment by benjaminjkraft** [comment]
I think [`use_struct_references`](https://github.com/Khan/genqlient/blob/main/docs/genqlient.yaml#L81), added in #155, is what you're looking for!  It's not in a release yet (see #163) but you can get it on latest main branch.

BTW, the directive is not written quite right, see #151.
