### ISSUE TITLE
Image in README is hard to read in GitHub's dark/dimmed mode

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/genqlient#17]
<img width="901" alt="Screen Shot 2021-04-21 at 9 43 41 PM" src="https://user-images.githubusercontent.com/1044413/115643424-bc4ad580-a2ea-11eb-88b2-734e739e257c.png">
<img width="906" alt="Screen Shot 2021-04-21 at 9 42 36 PM" src="https://user-images.githubusercontent.com/1044413/115643426-bc4ad580-a2ea-11eb-8223-816f3a9b5014.png">

**Comment by benjaminjkraft** [comment]
Hah, good point!  I guess I could do a white background, but that seems like it might be annoying too.  Or I could use some color.  Other ideas welcome.

**Comment by benjaminjkraft** [comment]
See also https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981.

**Comment by kevinbarabash** [comment]
SVG does support media queries so I think we could probably build an asset that reverses itself based on the browser settings.  If someone has their GitHub preferences to always use dark mode regardless of the browser setting it won't handle that case.

**Comment by benjaminjkraft** [comment]
Oh, interesting, good point!  I had switched from SVG to PNG so I didn't have to worry about fonts, but there are obviously other ways of handling that.  I'll take a look when I get a chance.

**Comment by benjaminjkraft** [comment]
@kevinbarabash your solution worked!  Subject to the caveat you gave, which I think is better than the alternatives.
