### ISSUE TITLE
Remap remote schemas with duplicate type names

### ISSUE THREAD

**Issue by Andrew-dob** [Khan/genqlient#177]
Since genqlient supports generation from multiple schemas, chances are people will run into duplicate type names across them. If using a copied remote schema, there isn't way to edit it ourselves and thus we run into an `invalid schema: Cannot redeclare type <Type>` error.

Would it be possible to add a prefix of the schema name to the types so the names don't conflict? Essentially re-mapping the schemas.

The current solutions offered for this are type extensions which would again require edits to the schemas which are not always possible.

**Comment by benjaminjkraft** [comment]
Hmm, I'm confused how it would work if you are using multiple incompatible schemas: when you write a query, how does it know which schema to use?  Do fields in one schema reference the other, or are they totally separate?

I think the idea of allowing multiple files is that those files might together comprise a single schema, but if the schemas don't compose, that won't work.  I might suggest just creating one genqlient config file for each schema, if that's something that would make sense for you.

**Comment by Andrew-dob** [comment]
Hey, the schemas are totally separate, and they might accidentally have duplicate names of common types or scalars.

After writing this suggestion I've split my schemas into separate folders with a genqlient config file in each and that does seem to work. I guess my initial thoughts were to be able to do something similar to schema stitching - either deduplicating identical types and only keeping one or transforming the schema so all types are prefixed with a schema name.

**Comment by benjaminjkraft** [comment]
Got it!  I think if the schemas are totally separate, keeping the genqlient configs separate is going to be the best approach for you.  I see what you mean about schema stitching, but I think if the only place we do it is at the schema level, for two totally separate schemas, it's going to feel really half-baked, while implementing a really full-featured approach to match schema-stitching servers (where the schemas might relate somehow, and genqlient might break your query into queries to multiple backends -- basically one of the GraphQL federation specs, but with the gateway on the client) is a huge project.  (A very interesting one! But huge.)

I'll keep thinking about what might make sense here -- and ideas for how we implement this without it being confusing are welcome -- but I think it's not going to be a good idea right away.  One possibility is to look at how possible it would be to integrate one of the federation implementations in Go to run on the client -- cc @dnerdy might have thoughts on whether that's an impossible project or merely a tricky one.
