### ISSUE TITLE
Help appreciated: Generate fields with omitempty for types in arrays

### ISSUE THREAD

**Issue by jenslauterbach** [Khan/genqlient#188]
I am trying to figure out how to use the `@genqlient` directive and would appreciate some help.

Consider the following mutation:

```graphql
mutation MyMutation($documents: [MyDocument!]!) {
    mutateSomething(documents: $documents)
}
```

The input that is used is of type `[MyDocument]`.  Image that type to look like this:

```graphql
input MyDocument {
    createdAt string
}
```

I wanted to achieve that the generated Go type has a JSON tag that uses the `omitempty` keyword. Based on the genqlient FAQ I needed to use the `@genclient()` directive, so I tried the following:

```graphql
# @genqlient(for: "MyDocument.createdAt", omitempty: true)
mutation MyMutation($documents: [MyDocument!]!) {
    mutateSomething(documents: $documents)
}
```

But this causes the following error:

```
for is only applicable to operations and arguments
```

All the help I could find always uses a single input type instead of an array. So it might be that I just use the wrong syntax.

Looking forward to your suggestions and help 😄

**Comment by benjaminjkraft** [comment]
Ah, yes, I think this is a syntax confusion, described further in #151.  The short answer is that you want something like
```graphql
# @genqlient(for: "MyDocument.createdAt", omitempty: true)
mutation MyMutation(
    # (or I think the directive can also go here?)
    $documents: [MyDocument!]!,
) {
    mutateSomething(documents: $documents)
}
```
until such time as genqlient gets clearer syntax.

**Comment by jenslauterbach** [comment]
@benjaminjkraft This worked! Thank you so much.

**Comment by pksunkara** [comment]
There's no difference between the two snippets. How is this fixed? I am encountering the same issue.

**Comment by benjaminjkraft** [comment]
The difference is where the line breaks are. Please see #151 for more details, or if you don't want to read all that just break up the line after any misbehaving directive until it works.
