### ISSUE TITLE
Lowercase the error massage, because go-staticcheck complains with ST1005

### ISSUE THREAD

**Issue by rdanchev** [Khan/genqlient#202]
`error strings should not be capitalized (ST1005) go-staticcheck`

https://github.com/Khan/genqlient/blob/37fa3d6e7c27b7772a3c77ef2287315a36738601/generate/unmarshal.go.tmpl#L142

**Comment by benjaminjkraft** [comment]
Thanks for the report; PRs are welcome for this sort of thing but please note that we do not intend for generated code to be lint-clean according to any particular style tool: linters enforce many guidelines that make sense for human-written code but not necessarily for generated code.
