### ISSUE TITLE
Using package_bindings in genqlient.yaml causes an error (v0.5.0)

### ISSUE THREAD

**Issue by danielnovograd** [Khan/genqlient#215]
**Describe the bug**
`package_bindings` was not included as part of v0.5.0, despite its inclusion in the changelog.

**To Reproduce**
Define `package_bindings` spec in `genqlient.yaml`
❌ 
```shell
go install github.com/Khan/genqlient
genqlient
```
✅ 
```shell
go install github.com/Khan/genqlient@main
genqlient
```

**Expected behavior**
Should not error and utilize existing models

**genqlient version**
v0.5.0

**Additional context**
Would be great to release this! Looks to be working on `main`

**Comment by benjaminjkraft** [comment]
Thanks for pointing that out! Looks like the merge did something confusing and added it to the existing changelog. I'll fix up the changelog, and look at when it makes sense to do a release.

**Comment by benjaminjkraft** [comment]
Changelog is fixed. #218 to release a new tagged version; I'm gonna wait at least a week or so to see if we get more feedback on this feature (see e.g. #220). In the meantime you can always install `genqlient@master`!
