### ISSUE TITLE
Release v0.6

### ISSUE THREAD

**Issue by benjaminjkraft** [Khan/genqlient#218]
It's been a few months; not that much is new but when we get a chance we should release a new version. Probably can be ~0.5.1 since there's not that much in it.~ 0.6 since it includes the Go version bump.

**Comment by benjaminjkraft** [comment]
@csilvers or @dnerdy I'm guessing you've pulled e3227388/#241 in at Khan? Once you have we can call that commit tested and I'll cut the release when I get a chance (maybe not for a few weeks though depending how busy I end up).

**Comment by csilvers** [comment]
Actually we haven't had a chance to make use of it yet.  I just wanted to get started on the genqlient part early since I know it can take time to cut a new release.

**Comment by benjaminjkraft** [comment]
#269
