### ISSUE TITLE
debug mode to print JSON body before it's sent out

### ISSUE THREAD

**Issue by cjvirtucio87** [Khan/genqlient#223]
**Is your feature request related to a problem? Please describe.**
I had trouble narrowing down the issue with my generated code and wanted to see the exact JSON body that's sent out as a GraphQL query. I had to clone the `genqlient` repo, manually add a print statement, and point to it using a [workspace file](https://go.dev/doc/tutorial/workspaces) to see it. I think printing this request when calling the generated code in a debug mode of some sort would do away with the need for this workaround.

**Describe the solution you'd like**
I'd like for the JSON body for the GraphQL query (such as the [one marshaled for a POST request](https://github.com/Khan/genqlient/blob/85e2e8dffd211c83a2be626474993ef68e44a242/graphql/client.go#L181)) to be printed out to STDERR, gated on perhaps a debug flag from an environment variable, or a flag/log level set on the [client itself](https://github.com/Khan/genqlient/blob/85e2e8dffd211c83a2be626474993ef68e44a242/graphql/client.go#L43). I specifically mention STDERR because this way intentional output can still be consumed as normal, while debug output can be piped somewhere else; for instance:

```bash
my-app -debug 2>/var/log/my-app.err | tee /var/log/my-app.out
```

**Describe alternatives you've considered**
The approach I took was to clone this repo and manually add a print statement after [this line](https://github.com/Khan/genqlient/blob/85e2e8dffd211c83a2be626474993ef68e44a242/graphql/client.go#L181). But that's extra work that can be done away with if we could just set a flag.

**Additional context**
N/A

**Comment by benjaminjkraft** [comment]
Thanks for raising this! 

Another workaround that may be better is to wrap up the HTTP client to log the request. [This post](https://dev.to/stevenacoffman/tripperwares-http-client-middleware-chaining-roundtrippers-3o00) describes the general approach; specifically it will look something like:
```go
// instead of:
httpClient := ... // http.DefaultClient or something else
client := graphql.NewClient(..., httpClient)
// do:
httpClient := ... // http.DefaultClient or something else
httpClient = &http.Client{Transport: RoundTripper(httpClient.Transport)}
client := graphql.NewClient(..., httpClient)
```
where the `RoundTripper` is similar to what's described in [this post](https://stackoverflow.com/a/69352388/904174), perhaps using `net/http/httputil.DumpRequestOut` to print the request.

Does that seem like it would work for you? If so we can try to document a bit more about how that would look. It's a bit sad to me that I don't see a package out there that provides useful utilities like this without writing those ~10 lines yourself, but I'm not sure that genqlient is the place to add that; if you do come across one let us know and we can document it.

**Comment by cjvirtucio87** [comment]
The transport wrapper will work for us.
