### ISSUE TITLE
Support for object parameters

### ISSUE THREAD

**Issue by blamarvt** [Khan/genqlient#230]
**Is your feature request related to a problem? Please describe.**
My schema is not validating, but I think it's valid GraphQL. I'm new at this but this is my schema so far:

```
schema {
  query: Query
}

type ProductOrderBy {
  field: String
  order: String
}

type Query {
  storeId: String
  itemId: String!
  product(itemId: String): Product
  searchModel(keyword: String, orderBy: ProductOrderBy): SearchResults
}

type SearchResults {
   products(pageSize: Int): [Product]
}

type Product {
  itemId: String
  identifiers: ProductIdentifiers
  keyProductFeatures: ProductFeatureItems
  specificationGroup: [ProductSpecificationGroup]
  pricing(storeId: String): ProductPricing
}

type ProductSpecificationGroup {
  specifications: [ProductSpecification]
}

type ProductSpecification {
  specName: String
  specValue: String
}

type ProductFeatureItems {
  keyProductFeaturesItems: [ProductFeatures]
}

type ProductFeatures {
  features: [ProductFeature]
}

type ProductFeature {
  name: String
  value: String
}

type ProductPricing {
  value: Float
  unitOfMeasure: String
}

type ProductIdentifiers {
  productLabel: String
}
```

The error I'm getting is:

```
schema.graphql:14: invalid schema: cannot use ProductOrderBy as argument orderBy because OBJECT is not a valid input type
```

This error makes sense if object types aren't supported by `genqlient` but I couldn't find any statements for or against support in any existing issues. When using tools like https://www.the-guild.dev/graphql/codegen I am able to generate code using the above schema.

**Describe the solution you'd like**
I would love for `genqlient` to support objects as input types.

**Describe alternatives you've considered**
I don't really have alternatives as this client is based off an existing API so I have to follow that API's specification.

**Comment by benjaminjkraft** [comment]
I believe the schema is incorrect: as the error message says, `ProductOrderBy` is a `type` (object) not an `input` (input object), so it can't be used as an argument. I'm not sure why The Guild's tooling isn't validating that; the state of schema validation in GraphQL libraries is unfortunately pretty inconsistent. But in any case, you'll need to change `ProductOrderBy` to be an input object.
