### ISSUE TITLE
 field package_bindings not found in type generate.Config

### ISSUE THREAD

**Issue by droslean** [Khan/genqlient#240]
This is happening in all tags. 

`go run github.com/Khan/genqlient@main` works fine, but we can't use the latest commits.

@benjaminjkraft Can you create a tag or a release that doesn't contain that bug or a new release with the latest code?

```sh
invalid config file `...genqlient.yaml`: yaml: unmarshal errors:
  line 7: field package_bindings not found in type generate.Config
```

**Comment by benjaminjkraft** [comment]
We do have #218 to do a release! But to set expectations -- I can't promise when I'll get to it. I'm not sure what you mean that you can't use the latest commits -- Go is fine with you using any commit you like; of course we do try to make sure releases are a little more stable, but that's part of why they take some time!
