### ISSUE TITLE
Ability to add headers to the HTTP request.

### ISSUE THREAD

**Issue by robstove** [Khan/genqlient#249]
**Is your feature request related to a problem? Please describe.**
We need to be able to provide certain headers to the request for the graphql endpoint (e.g. auth token). This appears to be missing.

**Describe the solution you'd like**
Add ability to provide http headers to the request.

**Describe alternatives you've considered**
It doesn't appear that the request is made available at any point in the request life cycle.

**Additional context**
na

Much appreciated...

**Comment by benjaminjkraft** [comment]
Check out the documentation here: https://github.com/Khan/genqlient/blob/main/docs/FAQ.md#-use-an-api-that-requires-authentication
