### ISSUE TITLE
Drop Go <1.18

### ISSUE THREAD

**Issue by benjaminjkraft** [Khan/genqlient#257]
This is useful because we can use generics. For example, #252 is gonna be a bit tricky to integration test in part because it would require build tagging a bunch of things. And we can also use generics internally which will probably have at least a little value.

None of this is urgent if people are still using older Go though. @csilvers or @dnerdy, have y'all upgraded to 1.18 yet? Any other users who are still on 1.17 or below?

**Comment by benjaminjkraft** [comment]
Another reason to get to 1.18 is so we can put our version in easily (i.e. finally do the thing that #127/#129 wanted to) via [runtime.DebugInfo](https://tip.golang.org/doc/go1.18#debug/buildinfo).

**Comment by StevenACoffman** [comment]
@benjaminjkraft We are in the process of upgrading to Go 1.19 from Go 1.16, but that has not been completed yet.

**Comment by csilvers** [comment]
> @benjaminjkraft We are in the process of upgrading to Go 1.19 from Go 1.16, but that has not been completed yet.

(I expect it will be completed in 1-2 weeks.)

That said, we have no plans to upgrade our genqlient before our go1.19 upgrade is complete, so I don't think landing this PR needs to block on us!
