### ISSUE TITLE
genqlient: command not found

### ISSUE THREAD

**Issue by lovgrandma** [Khan/genqlient#266]
**Describe the bug**
For some reason after I install genqlient using below command I still cannot run command line tool:

go get github.com/Khan/genqlient/graphql

**To Reproduce**
go get github.com/Khan/genqlient/graphql

**Expected behavior**
Run genqlient and run command line tool for generated code

**genqlient version**
github.com/Khan/genqlient v0.5.0

**Additional context**

**Comment by StevenACoffman** [comment]
Try:
```
go get github.com/Khan/genqlient
```

**Comment by benjaminjkraft** [comment]
What Steve said! Let us know if that doesn't work, or if you remember which documentation you got the command you ran from, so we can update it.
