### ISSUE TITLE
Support, new release

### ISSUE THREAD

**Issue by fedevilensky** [Khan/genqlient#321]
**Is your feature request related to a problem? Please describe.**
I want to use the generic optional type. But there is no new release since May of last year.

**Describe the solution you'd like**
I'd like to know if a new release is planned, or if it's ok to use main branch (and if so, can you guys add it to the readme)

**Comment by benjaminjkraft** [comment]
Good timing! I actually just wrote some [docs about releases](https://github.com/Khan/genqlient/pull/322/files?short_path=c1cc304#diff-c1cc304e56dd03cbb5cf65c32d83c9b7ab069800b2ce780249ac87d320e76789). But we should also do a new one soon since it's been a while, so I'll leave this open.
