### ISSUE TITLE
Allow globs for schema/queries to be optional, if at least one file is found

### ISSUE THREAD

**Issue by stormsweeper** [Khan/genqlient#327]
**Is your feature request related to a problem? Please describe.**
When running generation, and any glob in the config does not match any files, an error is returned and generation fails. 

In our particular case, we have current SQL-based files inside dirs in `lib/models`, and we'd like to put graphql operations in files in those directories. Thus:

```yaml
operations:
- "lib/models/*/*.graqhql"
```

However, we do have some nested models (e.g. `lib/models/foo/bar`), but if we add

```yaml
- "lib/models/*/*/*.graqhql"
```
then the generation will exit unless actual files exist. 

**Describe the solution you'd like**
Ideally, this should allow some globs to fail but warn instead. This would allow us to add/remove the query files as needed, without having to also update the genqlient config.

**Describe alternatives you've considered**
We could add/remove the directory lines as we add/remove the files. Just a bit of extra work.

**Additional context**

* previous issue about nested dirs: #167 
* previous issue that introduced current behavior: #146

**Comment by benjaminjkraft** [comment]
As I commented on #328 -- let's do #167 instead.
