### ISSUE TITLE
Inconsistent JSON Tag Generation for Required Boolean Fields in Structs

### ISSUE THREAD

**Issue by abiran** [Khan/genqlient#329]
I've encountered an issue with genqlient's code generation, particularly regarding how JSON tags are generated for required boolean fields within input structs. The issue arises in the context of a GraphQL schema where certain input fields are non-nullable (Boolean!), but the corresponding Go struct fields are sometimes generated with the omitempty JSON tag option, which is not expected for required fields.

Given a simplified GraphQL schema with a structure akin to the following:

```
input MyInputType {
  requiredField: Boolean!
}
```

And a mutation that utilizes this input:

```
mutation myMutation($input: MyInputType!) {
  myOperation(input: $input) {
    # response fields
  }
}
```

I would expect genqlient to generate a Go struct for MyInputType with a requiredField that does not include the omitempty option in its JSON tag, because the field is non-nullable in the GraphQL schema.

Expected

```
type MyInputType struct {
  RequiredField bool `json:"requiredField"`
}
```

Actual

```
type MyInputType struct {
  RequiredField bool `json:"requiredField,omitempty"`
}
```

**Steps to Reproduce**

1. Define a GraphQL schema with a non-nullable boolean field in an input type.
2. Generate Go client code using genqlient.
3. Observe the JSON tag for the non-nullable field in the generated Go struct.

**Impact**
This inconsistency can lead to runtime errors when executing mutations, as the GraphQL server may reject requests missing required fields. It also requires manual intervention to correct the generated code, which is not ideal for a code generation tool.

I hope this report helps to clarify the issue. I'm looking forward to any suggestions or workarounds, and I'm happy to provide further details if needed.

**Comment by benjaminjkraft** [comment]
This sounds plausibly like a bug! But can you provide a full repro? (A repo with the queries that we can look at, or just upload your schema, queries, and generated.go.) That will make it a lot easier to look into. If I recall correctly, we never add `omitempty` unless you told us to _somewhere_, so probably you did specify it somewhere and it's having effects in an unintended place.

**Comment by abiran** [comment]
@benjaminjkraft this is a small example of the schema

```
schema {
  mutation: Mutation
}

directive @oneOf on FIELD_DEFINITION | INPUT_OBJECT

scalar NonEmptyString

type Mutation {
  user: UserMutations!
}

type UserMutations {
  create(input: CreateUserInput!): CreateUserResponse!
}

input CreateUserInput @oneOf {
  admin: CreateUserAdminInput
  editor: CreateUserEditorInput
}

input CreateUserEditorInput {
  active: Boolean!
  name: NonEmptyString!
}

input CreateUserAdminInput {
  name: NonEmptyString!
  active: Boolean!
}

type CreateUserResponse {
  result: CreateUserResult!
}

union CreateUserResult = UserAdmin | UserEditor

type UserAdmin implements User & Node {
  id: ID!
}

type UserEditor implements User & Node {
  id: ID!
}

interface User implements Node {
  id: ID!
}

interface Node {
  id: ID!
}
```
after run `go run github.com/Khan/genqlient` we can see

```
type CreateUserEditorInput struct {
	Active bool   `json:"active"`
	Name   string `json:"name"`
}
``` 

having this is a small operation.graphql

```
mutation create_user($admin: CreateUserAdminInput, $editor: CreateUserEditorInput) {
  user {
    create(input: { admin: $admin, editor: $editor }) {
      result {
        ... on UserAdmin {
          id
        }
        ... on UserEditor {
          id
        }
      }
    }
  }
}
```

since the create accepts `@oneOf` there is no need to send both user bodies, but then we can receive a graphql error like

```
Exactly one key must be specified for input type "CreateUserInput"
```

if we add 

```
# @genqlient(omitempty: true)
```

on the top of the mutation to avoid this graphql error, then the operations.go auto generated file will result with this struct

```
type CreateUserEditorInput struct {
	Active bool   `json:"active,omitempty"`
	Name   string `json:"name,omitempty"`
}
```

When the active is still required, the only optional should be the whole body not a single component.

**Comment by benjaminjkraft** [comment]
Ah, I think this is just #151. You want
```
# @genqlient(omitempty: true)
mutation create_user(
  $admin: CreateUserAdminInput,
  $editor: CreateUserEditorInput,
) ...
```
(and yes that's super confusing, the issue has more discussion of what we could/should change)
