### ISSUE TITLE
Optional input with required output

### ISSUE THREAD

**Issue by ido-perez** [Khan/genqlient#331]
**Is your feature request related to a problem? Please describe.**
I want to generate the query input as optional (pointer: true) but the query response as required.

For example: 
```
query getExample($where: inputExample) {
  example(where: $where) {
    response
  }
}
```
The result will be:
`inputExample` fields will be optional (pointer: true)
`response` fields will be required

**Comment by benjaminjkraft** [comment]
There's a bunch of documentation about nullable fields! https://github.com/Khan/genqlient/blob/main/docs/operations.md#nullable-fields If you have a specific suggestion or request for something that doesn't exist, you'll need to be more specific about why none of the current options work for you.
