### ISSUE TITLE
Optional parameter made required

### ISSUE THREAD

**Issue by nelsonjr** [Khan/genqlient#337]
**Describe the bug**

For queries that have string parameters that are not `!`, the generator creates it as `string` instead of `*string`, making it impossible to use it, for example, on pagination cursors.

**To Reproduce**

Generate this query:

```
query Test($after: String) {
  projects(after: $after) {
    nodes {
      id
    }
  }
}
```

Observe that the test is:

```
func Test(
	ctx_ context.Context,
	client_ graphql.Client,
	after string,
) (*TestResponse, error) {
 ...
}
```

**Expected behavior**

For this query, after must be: `after *string`

**genqlient version**

`v0.7.0`

**Comment by benjaminjkraft** [comment]
Thanks for the post -- there's a bunch more documentation of genqlient's handling of nullability (by default and config options) here: https://github.com/Khan/genqlient/blob/main/docs/operations.md#nullable-fields

**Comment by nelsonjr** [comment]
Thanks, Ben, for the pointers!
