### ISSUE TITLE
Set up OSS stuff

### ISSUE THREAD

**Issue by benjaminjkraft** [Khan/genqlient#35]
- [x] Add to khan.github.io (Khan/khan.github.io#17)
- [x] Contribution guidelines
  - [x] CLA (#96)
  - [x] COC (#96)
  - [x] Contributor-focused docs (#96)
  - [x] "Good first issue"/"help wanted"
- [x] Issue templates (#96)
- [ ] tag a v0.1.0

**Comment by kevinbarabash** [comment]
The CLA form lives at https://www.khanacademy.org/r/cla, but our CLA bot is currently out of commission.
