### ISSUE TITLE
Remove common prefix from all query-names

### ISSUE THREAD

**Issue by benjaminjkraft** [Khan/genqlient#41]
At Khan we prefix all of our queries with the service-name, e.g. `Coaches_GetAssignments`, so that the names are globally unique (useful for logs).  But in the generated types, this prefix is just noise.  It would be nice to find a way to remove it; except it's a bit hard to do so in a generalizable way.

Another option would be to munge the query to add to the "real" operation name -- that is you would just write `query GetAssignments` and genqlient would know based on your config to send `Coaches_GetAssignments`.

**Comment by csilvers** [comment]
I'm inclined to just leave it as it is now.  How bad is it to have that noise in the generated types?  The generated types are already super-long; if I want to use them in real life I make a type alias for them anyway.

**Comment by benjaminjkraft** [comment]
Ok, if you don't feel this has been an issue in practice I'll just close it!  It doesn't cost us anything other than longer names (for both the query-function and the types).

**Comment by csilvers** [comment]
Yeah, it's not been an issue for me.  I mean, the long names are unreadable in general, but I don't think adding the `Coach_` prefix makes them worse.
